### ISSUE TITLE
数据能不能更详尽一点

### ISSUE THREAD

**Issue by Victor-YanXiaoZhong** [xkloveme/utools-weather#3]
数据能不能更详尽一点，比如有个按小时点的天气情况

**Comment by Victor-YanXiaoZhong** [comment]
定位也不准，一直是北京，我选择了昆明，也没有加载我本地的天气
![image](https://user-images.githubusercontent.com/13307736/86562182-d18d8800-bf94-11ea-935d-9f57c4b12b71.png)

**Comment by xkloveme** [comment]
数据目前只有这些了,可能后续会增加,但是也不确定,定位不准确可能是主框架原因,现在我看是好的
